config/routes.rb
SampleApp1::Application.routes.draw do
  resources :users do 
    collection do 
      get '/signup' => 'users#new'
    end
  end
  resources :businesses do 
    collection do 
      get '/signup' => 'businesses#new'
    end
  end

  resources :sessions,        only: [:new, :create, :destroy]
  resources :calendars,       only: [:create, :destroy]
  resources :products

  root to: 'static_pages#home'
  get '/signin',                      to: 'sessions#new'
  delete '/signout',                     to: 'sessions#destroy'
  get '/help',                        to: 'static_pages#help'
  get '/about',                       to: 'static_pages#about'
  get '/contact',                     to: 'static_pages#contact'
  get '/scheduled_jobs/:id',            to: 'calendars#show',           as: 'scheduled_jobs'
  get '/calendar/:id/calendar_items',   to: 'calendar_items#show',  as: 'show_calendar_items'

end
          

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		@calendar = current_user.calendars.build
  		@feed_items = current_user.feed.paginate(page: params[:page])
      if business? 
        @product = current_user.products.build
        @business = current_user
        render 'businesses/show'
      else
        @user = current_user
        @businesses = Business.all
        render 'users/show'
      end
  	end
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

  <div id="main" role="main">

	<!-- Section #1 / Intro -->
	<section id="first" class="story" data-speed="8" data-type="background">    	
		<!-- <div class="smashinglogo" data-type="sprite" data-offsetY="100" data-Xposition="50%" data-speed="0"></div>		 -->
		<article style="font-family: 'Cabin Sketch', cursive;font-size:4em;">

			<!-- <img src="assets/tutorial-title.png" alt="tutorial-title" width="711" height="242" /> -->
			<p> I would like to tell you a story...</p>
	    	<p>Once upon a time...</p>		
	    </article>
	</section>

	<!-- Section #2 / Background Only -->
	<section id="second" class="story" data-speed="4" data-type="background">
		<article  style="font-family: 'Cabin Sketch', cursive;font-size:4em;">
	    	<p>A guy was trying to organize himself, making notes of all his duties...</p>		
		</article>
	</section>

	<!-- Section #2 / Background Only -->
	<section id="third" class="story" data-speed="4" data-type="background" data-offsetY="350">
		<article  style="font-family: 'Cabin Sketch', cursive;font-size:4em;">
	    	<p>He ended up with loads of paper around...</p>		
		</article>
	</section>
	<section id="fourth" class="story" data-speed="4" data-type="background" data-offsetY="500">
		<div class="googlecalendar" data-type="sprite" data-offsetY="2150" data-Xposition="85%" data-speed="2"></div>
		<div class="icalendar" data-type="sprite" data-offsetY="2250" data-Xposition="60%" data-speed="2"></div>
		<article  style="font-family: 'Cabin Sketch', cursive;font-size:4em;">
	    	<p>Then he tried to use automated online resources to help him and clean up this mess...</p>		
		</article>
	</section>
	<section id="fifth" class="story" data-speed="4" data-type="background" data-offsetY="950">
		<article  style="font-family: 'Cabin Sketch', cursive;font-size:4em;">
	    	<p>It worked! But how can I optimize my time?...</p>		
		</article>
	</section>
	<section id="sixth" class="story" data-speed="4" data-type="background" data-offsetY="1300">
		<article  style="font-family: 'Cabin Sketch', cursive;font-size:4em;">
	    	<p>I know! Instead of remembering me what I need to do, it just do and tell me it is done! =)</p>		
		</article>
	</section>
	<section id="theend" class="story" data-speed="4" data-type="background" data-offsetY="1500">
		<article  style="font-family: 'Cabin Sketch', cursive;font-size:4em;">
	    	<p>Go to the beach and relax! =)</p>		
		</article>
	</section>
		
	<!-- Section #3 / Photos -->
	<!-- <section id="third" class="story" data-speed="6" data-type="background" data-offsetY="250">    	
		<div class="photograph" data-type="sprite" data-offsetY="1250" data-Xposition="25%" data-speed="2"></div>
    	<article>
    		<h2>Scrolling Sprites</h2>
	    	<div class="textbox">    	
		    	<p>The next step in your parallax scrolling adventure is to create some sprites!</p>
		    	<p>I have cut out one of the photos in this background and use it as a sprite. It scrolls at a different speed to the background <i>and</i> the window, and it's this effect that's used so well on Nike Better World and other parallax sites..</p>
		    	<p>Using too many sprites can slow down older computers, and you need to use some clever maths (and trial & error!) to work out their placement on the page.</p>
		    </div>
    	</article>
	</section>	
	

	<!-- Section #4 / HTML5 Video -->
	<!-- <section id="fourth" class="story" data-speed="8" data-type="background" data-offsetY="250">
    	<article>
    		<h2>HTML5 Video</h2>
	    	<div class="textbox">    	
		    	<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
		    	<p>Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
		    	<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. o.</p>
		    </div>
    	</article>
		<video controls width="640" width="480" data-type="video" data-offsetY="2400" data-speed="1.5">
			<source src="video/parallelparking.theora.ogv" type="video/ogg" />
			<source src="video/parallelparking.mp4" type="video/mp4" />
			<source src="video/parallelparking.webm" type="video/webm" />
		</video>
	</section>	 -->

	<!-- Section #5 / The End-->
	<!-- <section id="theend" class="story" data-speed="8" data-type="background" data-offsetY="250">    	
		<div class="byebye" data-type="sprite" data-offsetY="-1600" data-Xposition="50%" data-speed="-2"></div>	
	</section> -->
	
  </div> <!-- // End of #main -->



  <!-- Our Javascript, starting with jQuery -->
  <!--[if lt IE 7 ]>
    <script src="js/libs/dd_belatedpng.js"></script>
    <script>DD_belatedPNG.fix("img, .png_bg");
  <![endif]-->

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact me at magnomathias21@gmail.com.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span3">
      <section>
        <%= render 'shared/user_info' %>
      </section>
    </aside>
    <% if business? %>
      <aside class="span7">
        <h3>Product Feed</h3>
        <section>
          <%= render 'shared/product_form' %>
        </section>
        <section>
          <%= render 'shared/feed' %>
        </section>
      </aside>
    <% else %>
      <aside class="span7">
        <h3>Create your Schedule7y7y</h3>
      </aside> 
    <% end %>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to Cron it</h1>

    <h2>
      This is a trial application.
    </h2>

    <%= link_to "Sign up as a user now!", signup_users_path, class: "btn btn-large btn-primary" %>
    <%= link_to "Sign up as a business now!", signup_businesses_path, class: "btn btn-large btn-primary" %>
  </div>
<% end %>