config/routes.rb
SampleApp1::Application.routes.draw do
  resources :users do 
    collection do 
      get '/signup' => 'users#new'
    end
  end
  resources :businesses do 
    collection do 
      get '/signup' => 'businesses#new'
    end
  end

  resources :sessions,        only: [:new, :create, :destroy]
  resources :calendars,       only: [:create, :destroy]
  resources :products

  root to: 'static_pages#home'
  get '/signin',                      to: 'sessions#new'
  delete '/signout',                     to: 'sessions#destroy'
  get '/help',                        to: 'static_pages#help'
  get '/about',                       to: 'static_pages#about'
  get '/contact',                     to: 'static_pages#contact'
  get '/scheduled_jobs/:id',            to: 'calendars#show',           as: 'scheduled_jobs'
  get '/calendar/:id/calendar_items',   to: 'calendar_items#show',  as: 'show_calendar_items'

end
          

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :business
	has_many :calendars_products, class_name: "CalendarProduct", dependent: :destroy
	validates :name, presence: true, length: { maximum: 50 }	
	validates :description, presence: true, length: { maximum: 150 }	
	validates :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    @business  = current_user
    @products  = @business.products.paginate(page: params[:page])
    @product = Product.new
  end

  def create

    @product = current_user.products.create(product_params)
    if @product.save
      flash[:success] = "Product created!"
      redirect_to products_path
    else
      flash[:error] = "Error creating product!"
      render 'index'
    end
  end

  def edit
    @product = current_user.products.find(params[:id])
  end

  def update
    @product = current_user.products.find(params[:id])

    if @product.update_attributes(product_params)
      flash[:success] = "Product updated!"
      redirect_to products_path
    else
      flash[:error] = "Error updating product!"
      render 'index'
    end
  end

  def show
    @business  = current_user
    @products  = @business.products.paginate(page: params[:page])
    @product = @business.products.find(params[:id])
    render 'index'
  end
  
  def destroy 
    @product.destroy
		redirect_to products_path
  end

  private 
    def product_params
      params.require(:product).permit(:name, :description, :picture_url, :price, actions_attributes: [:command, :_destroy])
    end
    
    def correct_user
      @product = current_user.products.find_by(id: params[:id])
      redirect_to root_url if @product.nil?
    end

end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  Name:
  <div class="field">
    <%= f.text_field :name%>
  </div>
  Description:
  <div class="field">
    <%= f.text_field :description%>
  </div>
  Picture URL:
  <div class="field">
    <%= f.text_field :picture_url%>
  </div>
  Price:
  <div class="field">
    <%= f.text_field :price%>
  </div>
  <% if @product.persisted? %>
    <%= f.submit "Save", class: "btn btn-large btn-primary" %>
    <%= link_to "Cancel", products_path,data: {confirm: "You sure?"}%>
  <% else %>
    <%= f.submit "Add", class: "btn btn-large btn-primary" %>

  <% end %>
<% end %>

app/views/products/_list_products_for_schedule.html.erb
<% if business.products.any? %>
  	<section id="business-<%= business.id %>" class="business-products">
		<h3>Products (<%= business.products.count %>)</h3>
    	<%= render business.products %>
  	</section>
<% end %>

app/views/products/_product.html.erb
<li id="<%= product.id %>">
  <div class="counter"></div>
  <div class="show-field">
    <span class="content"><%= product.name %></span>
  </div>
  <div class="show-image">
    <img src="<%= product.picture_url %>"/>
  </div>
  <div class="show-field">
    <span class="content"><%= product.price %> </span>
  </div>
</li>

app/views/products/_show.html.erb
<li id="<%= product.id %>">
  <span class="title">Product ID #<%= product.id %> </span>
  <div class="show-field">
    <span class="content-label">Name:</span>
    <span class="content"><%= product.name %></span>
  </div>
  <div class="show-field">
    <span class="content-label">Description:</span>
    <span class="content"><%= product.description %> </span>
  </div>  
  <div class="show-field">
    <span class="content-label">Picture URL:</span>
    <span class="content"><%= product.picture_url %> </span>
  </div>
  <div class="show-field">
    <span class="content-label">Price:</span>
    <span class="content"><%= product.price %> </span>
  </div>
  <span class="timestamp">
    Posted <%= time_ago_in_words(product.created_at) %> ago.
  </span>
  <% if current_user?(product.business) %>
    <%= link_to "delete", product, method: :delete,data: {confirm: "You sure?"}, title: product.id %>
    <%= link_to "edit", product_path(product) %>
  <% end %>
</li>

app/views/products/edit.html.erb
<% render 'form' %>

app/views/products/index.html.erb
<% provide(:title, @business.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @business %>
        <%= @business.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <section>
      <h3>Create a Product</h3>
      <%= render 'form' %>
    </section>
    <% if @products.any? %>
      <h3>Products (<%= @products.count %>)</h3>
      <ol class="products">
        <%= render partial: 'show', collection: @products, as: :product %>
      </ol>
      <%= will_paginate @products %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<% render 'form' %>