config/routes.rb
SampleApp1::Application.routes.draw do
  resources :users do 
    collection do 
      get '/signup' => 'users#new'
    end
  end
  resources :businesses do 
    collection do 
      get '/signup' => 'businesses#new'
    end
  end

  resources :sessions,        only: [:new, :create, :destroy]
  resources :calendars,       only: [:create, :destroy]
  resources :products

  root to: 'static_pages#home'
  get '/signin',                      to: 'sessions#new'
  delete '/signout',                     to: 'sessions#destroy'
  get '/help',                        to: 'static_pages#help'
  get '/about',                       to: 'static_pages#about'
  get '/contact',                     to: 'static_pages#contact'
  get '/scheduled_jobs/:id',            to: 'calendars#show',           as: 'scheduled_jobs'
  get '/calendar/:id/calendar_items',   to: 'calendar_items#show',  as: 'show_calendar_items'

end
          

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://magnomathias.com/">Blog</a>
    by Magno Mathias
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container-header">
      
      <div class="logo">
        <span class="logo-cron">
          Cron
        </span>
        <span class="logo-it">
          IT
        </span>
      </div>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <% if business? %>
              <!--<li><%= link_to "Users", users_path %></li>-->
              <li><%= link_to "Products", products_path %></li>
            <% else %>
              <li><%= link_to "Scheduled Jobs", scheduled_jobs_path(current_user) %></li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Cabin+Sketch:700|Bangers' rel='stylesheet' type='text/css'>
    <%= render 'layouts/shim' %>    
  </head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>